### ISSUE TITLE
When atom-flow is enabled, atom-haxe cannot spawn 'haxelib'

### ISSUE THREAD

**Issue by jonathonyule** [snowkit/atom-haxe#47]
I am getting this error when I have atom-flow enabled

<img width="450" alt="screenshot 2015-10-31 20 13 32" src="https://cloud.githubusercontent.com/assets/1854484/10866589/fe10f7a4-800b-11e5-8dcc-36370bb59dba.png">

I've tried setting the haxelib location in atom-haxe settings to multiple locations including '/usr/local/bin/', '/usr/local/bin/haxelib' and even the location I have the libraries 'Users/jonathonyule/dev/haxelib'.

Any help or points in the right direction would help a lot

**Comment by jonathonyule** [comment]
Launching Atom from the command line fixes this

**Comment by ruby0x1** [comment]
Are you on OSX? 
This is because of how a command is spawned, and on latest osx + latest haxe the full PATH is not loaded meaning it can't find it. 

Another option immediate term (till we fix this in the plugin) is to set the exact path to haxe and haxelib in the settings.

![](https://i.imgur.com/q3c3key.png)

**Comment by jonathonyule** [comment]
I'm on the latest El Capitan 10.11.1

The warning for haxe not spawning appeared until I filled in the path like you have there but when trying the same with the haxelib path it kept giving the error even with the exact path

**Comment by lewislepton** [comment]
hmmm. i have tried the re-issue of the path. but still the error pops up. sadly. will wait for the update ;)

**Comment by jeremyfa** [comment]
Specifying the path as a workaround should be effective though. I updated to El Capitan, set haxe and haxelib paths in the haxe package settings and got it working.

**Comment by lewislepton** [comment]
hmmm. weird. tried. but no dice. odd...

**Comment by jtruher** [comment]
I'm seeing the same error.  Even running `which haxelib` and sticking that into the haxelib location field doesn't appear to help.  It's interesting that it seems to find `haxe`, but not `haxelib`, though it's entirely possible that I'm misinterpreting load order.

**Comment by jeremyfa** [comment]
Mmmh, it seems that there is a direct call to `haxelib` in the [atom-flow](https://github.com/snowkit/atom-flow) plugin: https://github.com/snowkit/atom-flow/blob/65266746c6bf9a451f1079ebd87bb394b3c6ad9d/lib/flow-call.js#L17

That might be the reason why the error still pops out. Haxe plugin itself (without flow, just hxml file) should work fine after setting configuration, however. Can you confirm this?

**Comment by ruby0x1** [comment]
Try update the packages: should be fixed in 
atom-haxe v0.8.9
atom-flow v0.5.1

**Comment by thoughton** [comment]
The fix works brilliantly for me - thank you!

**Comment by ruby0x1** [comment]
will reopen if not fixed for the majority, but both obvious causes are fixed.

**Comment by lewislepton** [comment]
hmmm. im still getting this strange
`'haxelib' could not be spawned...`

i did do the update and restrated plus updated the latest atom as well. but still. problem.s

i also took out the path things as well, restarted, but no. really weird to say the least

**Comment by lewislepton** [comment]
plus i get all of this psawning as well on the side

<img width="669" alt="screen shot 2015-11-19 at 10 31 49" src="https://cloud.githubusercontent.com/assets/11299322/11268534/3adf5530-8ea9-11e5-8f7e-722b711003e6.png">

**Comment by ruby0x1** [comment]
This looks an error with the installation of Atom somehow, given that it's having trouble running it's own internal components. I'm not entirely sure how to debug that, my instinct is to reinstall atom from a clean slate, or run Disk Utility (is that Mac?) and run fix permissions, especially if you upgraded over a few OS major releases on the same install.

**Comment by jeremyfa** [comment]
By the way, atom-lime needs to be fixed for this as well (in case any of the people here is using it)

Edit: I will do that in few hours.

**Comment by lewislepton** [comment]
hmmm. well the clean install seems to have worked... so far. but ill let you know if there is a problem.

aye. i use lime ;) so yeah a fix is needed ;)

**Comment by ruby0x1** [comment]
The fix will be upstream for lime pretty soon. Thanks for reporting back.

**Comment by lewislepton** [comment]
cool spot... thanks ;)

**Comment by jeremyfa** [comment]
The fix is live for the lime plugin. Tell me if it works for you!

**Comment by lewislepton** [comment]
@jeremyfa 
cool spot. though im actually still getting a error message saying there is no active lime. which is starnge. because i do the right click and select the xml sheet. i might try completely uninstalling again and try again

**Comment by ruby0x1** [comment]
If you're having further/other issues please file them at the appropriate repo
